import { StyleSheet } from "react-native";
import { PRIMARY_COLOR_RED } from "../../../theme/colors";

const style = StyleSheet.create({
  container: {
    paddingHorizontal: 22,
    marginTop: 24,
  },
  headerRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 24,
  },
  cancelButton: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: PRIMARY_COLOR_RED,
    paddingHorizontal: 16,
    paddingVertical: 6,
    borderRadius: 999,
  },
  cancelText: {
    color: "#FFFFFF",
    fontSize: 16,
    fontWeight: "600",
  },
  title: {
    fontSize: 28,
    fontWeight: "600",
    color: "#000000",
  },
  //   formSection: {
  //     flexShrink: 0,
  //   },
  //   label: {
  //     fontSize: 16,
  //     fontWeight: "500",
  //     color: "#111",
  //     marginBottom: 8,
  //     marginTop: 10,
  //   },
  //   textInput: {
  //     borderWidth: 1.5,
  //     borderColor: "#D1D5DB",
  //     borderRadius: 8,
  //     backgroundColor: "#FFFFFF",
  //     paddingHorizontal: 16,
  //     paddingVertical: 12,
  //     fontSize: 16,
  //     color: "#000",
  //     marginBottom: 20,
  //   },
  //   urgentRow: {
  //     flexDirection: "row",
  //     alignItems: "center",
  //     gap: 10,
  //   },
  //   urgentLabel: {
  //     fontSize: 16,
  //     color: "#111",
  //     fontWeight: "500",
  //   },
  //   statusRow: {
  //     flexDirection: "row",
  //     marginTop: 16,
  //     gap: 16,
  //   },
  //   statusDropdownWrapper: {
  //     flex: 1,
  //     position: "relative",
  //     zIndex: 10,
  //   },
  //   statusSelector: {
  //     flexDirection: "row",
  //     alignItems: "center",
  //     borderWidth: 1,
  //     borderColor: "#DDD",
  //     paddingHorizontal: 16,
  //     paddingVertical: 12,
  //     backgroundColor: "#FFFFFF",
  //   },
  //   statusSelectorText: {
  //     fontSize: 18,
  //     color: "#000",
  //     marginLeft: 12,
  //   },
  //   statusDropdownMenu: {
  //     position: "absolute",
  //     top: "100%",
  //     left: 0,
  //     right: 0,
  //     marginTop: 8,
  //     backgroundColor: "#FFFFFF",
  //     borderRadius: 18,
  //     paddingVertical: 8,
  //     shadowColor: "#000",
  //     shadowOpacity: 0.18,
  //     shadowRadius: 8,
  //     shadowOffset: { width: 0, height: 4 },
  //     elevation: 6,
  //     zIndex: 20,
  //   },
  //   statusOptionRow: {
  //     paddingHorizontal: 16,
  //     paddingVertical: 10,
  //   },
  //   statusOptionText: {
  //     fontSize: 18,
  //     color: "#000",
  //   },
  //   statusFrequencyHeaderRow: {
  //     flexDirection: "row",
  //     alignItems: "center",
  //     marginTop: 12,
  //     marginBottom: 4,
  //   },
  //   statusSummaryLeft: {
  //     flex: 1,
  //     flexDirection: "row",
  //     alignItems: "center",
  //   },
  //   statusSummaryLabel: {
  //     fontSize: 16,
  //     color: "#888",
  //     marginRight: 4,
  //   },
  //   statusSummaryValue: {
  //     flexDirection: "row",
  //     alignItems: "center",
  //   },
  //   statusSummaryText: {
  //     fontSize: 16,
  //     color: "#000",
  //   },
  //   dateRow: {
  //     flexDirection: "row",
  //     justifyContent: "space-between",
  //     alignItems: "center",
  //     gap: 16,
  //   },
  //   dateButtonWrapper: {
  //     flex: 1,
  //   },
  //   dateButton: {
  //     flexDirection: "row",
  //     alignItems: "center",
  //     justifyContent: "center",
  //     backgroundColor: PRIMARY_COLOR_BLUE,
  //     paddingVertical: 14,
  //     borderRadius: 6,
  //   },
  //   dateButtonText: {
  //     color: "#FFFFFF",
  //     fontSize: 16,
  //   },
  //   frequencyWrapper: {
  //     flex: 1,
  //   },
  //   frequencyDropdownWrapper: {
  //     position: "relative",
  //     zIndex: 10,
  //   },
  //   frequencySelector: {
  //     flexDirection: "row",
  //     alignItems: "center",
  //     borderRadius: 14,
  //     borderWidth: 1,
  //     borderColor: "#DDD",
  //     paddingHorizontal: 16,
  //     paddingVertical: 14,
  //     backgroundColor: "#FFFFFF",
  //     width: "100%",
  //   },
  //   frequencySelectorText: {
  //     fontSize: 18,
  //     color: "#000",
  //     marginLeft: 12,
  //     flexShrink: 0,
  //   },
  //   frequencyDropdownMenu: {
  //     position: "absolute",
  //     top: "100%",
  //     left: 0,
  //     right: 0,
  //     width: "100%",
  //     marginTop: 8,
  //     backgroundColor: "#FFFFFF",
  //     borderRadius: 18,
  //     paddingVertical: 8,
  //     shadowColor: "#000",
  //     shadowOpacity: 0.18,
  //     shadowRadius: 8,
  //     shadowOffset: { width: 0, height: 4 },
  //     elevation: 6,
  //     zIndex: 20,
  //   },
  //   frequencyOptionRow: {
  //     paddingHorizontal: 16,
  //     paddingVertical: 10,
  //   },
  //   frequencyOptionText: {
  //     fontSize: 18,
  //     color: "#000",
  //   },
  //   dueDateRow: {
  //     flexDirection: "row",
  //     alignItems: "center",
  //     marginTop: 12,
  //   },
  //   dueDateLabel: {
  //     fontSize: 16,
  //     color: "#888",
  //     marginRight: 4,
  //   },
  //   dueDateValue: {
  //     fontSize: 16,
  //     color: "#000",
  //     fontWeight: "500",
  //   },
  //   calendarOverlay: {
  //     flex: 1,
  //     backgroundColor: "rgba(0,0,0,0.25)",
  //     justifyContent: "center",
  //     alignItems: "center",
  //   },
  //   calendarCloseButton: {
  //     marginTop: 8,
  //     alignSelf: "flex-end",
  //     paddingHorizontal: 12,
  //     paddingVertical: 6,
  //     borderRadius: 999,
  //     backgroundColor: "#EFEFEF",
  //   },
  //   calendarCloseText: {
  //     fontSize: 14,
  //     color: "#111",
  //   },
  //   calendarCard: {
  //     width: "90%",
  //     borderRadius: 18,
  //     backgroundColor: "#FFFFFF",
  //     padding: 12,
  //     shadowColor: "#000",
  //     shadowOpacity: 0.18,
  //     shadowRadius: 8,
  //     shadowOffset: { width: 0, height: 4 },
  //     elevation: 8,
  //   },
  //   assigneeSection: {
  //     marginTop: 16,
  //     position: "relative",
  //   },
  //   assigneeHeaderRow: {
  //     flexDirection: "row",
  //     alignItems: "center",
  //   },
  //   assigneeButtonWrapper: {
  //     flexShrink: 0,
  //   },
  //   assigneeButton: {
  //     flexDirection: "row",
  //     alignItems: "center",
  //     justifyContent: "center",
  //     backgroundColor: PRIMARY_COLOR_BLUE,
  //     paddingVertical: 14,
  //     paddingHorizontal: 20,
  //     borderRadius: 8,
  //   },
  //   assigneeButtonText: {
  //     color: "#FFFFFF",
  //     fontSize: 16,
  //     fontWeight: "500",
  //   },
  //   rotationWrapper: {
  //     flexDirection: "row",
  //     alignItems: "center",
  //     marginLeft: 16,
  //     flexShrink: 1,
  //   },
  //   rotationLabel: {
  //     fontSize: 16,
  //     color: "#111",
  //     marginLeft: 8,
  //     flexShrink: 1,
  //   },
  //   assigneeSummaryRow: {
  //     flexDirection: "row",
  //     alignItems: "center",
  //     marginTop: 8,
  //   },
  //   assigneeSummaryLabel: {
  //     fontSize: 16,
  //     color: "#888",
  //     marginRight: 8,
  //   },
  //   assigneeSummaryValue: {
  //     flexDirection: "row",
  //     alignItems: "center",
  //   },
  //   assigneeAvatar: {
  //     width: 36,
  //     height: 36,
  //     borderRadius: 18,
  //     overflow: "hidden",
  //     marginRight: 12,
  //     backgroundColor: "#F1F1F1",
  //     justifyContent: "center",
  //     alignItems: "center",
  //   },
  //   assigneeAvatarImage: {
  //     width: "100%",
  //     height: "100%",
  //   },
  //   assigneeSummaryName: {
  //     fontSize: 16,
  //     color: "#000",
  //   },
  //   assigneeOverlay: {
  //     flex: 1,
  //     backgroundColor: "rgba(0,0,0,0.25)",
  //     justifyContent: "center",
  //     alignItems: "center",
  //   },
  //   assigneeCard: {
  //     width: "90%",
  //     maxHeight: "70%",
  //     borderRadius: 24,
  //     backgroundColor: "#FFFFFF",
  //     paddingHorizontal: 16,
  //     paddingVertical: 12,
  //     shadowColor: "#000",
  //     shadowOpacity: 0.18,
  //     shadowRadius: 8,
  //     shadowOffset: { width: 0, height: 4 },
  //     elevation: 8,
  //   },
  //   assigneeHeader: {
  //     flexDirection: "row",
  //     alignItems: "center",
  //     justifyContent: "space-between",
  //     marginBottom: 8,
  //   },
  //   assigneeTitle: {
  //     fontSize: 18,
  //     fontWeight: "600",
  //     color: "#111",
  //   },
  //   assigneeRow: {
  //     flexDirection: "row",
  //     alignItems: "center",
  //     paddingVertical: 10,
  //   },
  //   assigneeAvatarPlaceholder: {
  //     width: 36,
  //     height: 36,
  //     borderRadius: 24,
  //     marginRight: 16,
  //     backgroundColor: "#F1F1F1",
  //     justifyContent: "center",
  //     alignItems: "center",
  //   },
  //   assigneeName: {
  //     fontSize: 18,
  //     color: "#111",
  //   },
  //   descriptionInput: {
  //     borderWidth: 1.5,
  //     borderColor: "#E5E7EB",
  //     borderRadius: 18,
  //     backgroundColor: "#FFFFFF",
  //     paddingHorizontal: 16,
  //     paddingVertical: 20,
  //     fontSize: 16,
  //     color: "#000",
  //     marginTop: 8,
  //     marginBottom: 20,
  //     minHeight: 120,
  //   },
  //   createButtonWrapper: {
  //     marginTop: 8,
  //   },
  //   createButton: {
  //     flexDirection: "row",
  //     alignItems: "center",
  //     justifyContent: "center",
  //     backgroundColor: PRIMARY_COLOR_BLUE,
  //     paddingVertical: 16,
  //     borderRadius: 999,
  //     shadowColor: "#000",
  //     shadowOpacity: 0.15,
  //     shadowRadius: 8,
  //     shadowOffset: { width: 0, height: 4 },
  //     elevation: 4,
  //   },
  //   createButtonText: {
  //     color: "#FFFFFF",
  //     fontSize: 20,
  //     fontWeight: "700",
  //   },
});

export default style;
