apiVersion: v1
kind: Service
metadata:
  name: tasqly-backend
  namespace: tasqly-prod
  labels:
    app.kubernetes.io/name: tasqly
    app.kubernetes.io/component: backend
    app.kubernetes.io/environment: prod
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: tasqly
    app.kubernetes.io/component: backend
  ports:
    - name: http
      port: 8080
      targetPort: 8080