spring:
  application:
    name: backend

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true
    locations: classpath:db/migrations

management:
  endpoints:
    web:
      exposure:
        include: health

tasqly:
  security:
    jwt:
      issuer: tasqly
      expiration-minutes: 60
