spring:
  application:
    name: backend
  datasource:
    url: jdbc:postgresql://localhost:5432/tasqly
    username: tasqly_admin
    password: tasqly_password
    driver-class-name: org.postgresql.Driver
    jpa:
      hibernate:
        ddl-auto: update
      database-platform: org.hibernate.dialect.PostgreSQLDialect
