spring:
  mvc:
    throw-exception-if-no-handler-found: true

  web:
    resources:
      add-mappings: false

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true
    locations: classpath:db/migrations

tasqly:
  security:
    jwt:
      secret: "local-secret-local-secret-local-secret-123456"
      issuer: tasqly-test
      expiration-minutes: 60