spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tasqly
    username: tasqly_admin
    password: tasqly_password

tasqly:
  security:
    jwt:
      secret: "local-secret-local-secret-local-secret-123456"